version: '3.7'

services:
    server:
      image: usefathom/fathom:version-1.2.1
      environment:
        FATHOM_DATABASE_DRIVER: postgres
        FATHOM_DATABASE_URL: postgres://fathom:${POSTGRES_PASSWORD}@db:5432/fathom?sslmode=disable
      depends_on:
        - db
      deploy:
        labels:
          traefik.enable: "true"
          traefik.http.routers.fathom.entrypoints: https
          traefik.http.routers.fathom.tls.certresolver: letsencrypt
          traefik.http.routers.fathom.rule: Host(`${DOMAIN_FATHOM:?err}`)
          traefik.http.services.fathom.loadbalancer.server.port: "8080"
      networks:
        - internal
        - external

    db:
      image: postgres:17
      environment:
        POSTGRES_DB: fathom
        POSTGRES_USER: fathom
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      volumes:
        - postgres_data_volume:/var/lib/postgresql/data
      networks:
        - internal
volumes:
  postgres_data_volume:
    driver_opts:
      type: nfs
      o: "addr=${NFS_SERVER:?err},nfsvers=4,nolock,soft,rw"
      device: :/mnt/data/fathom/db

networks:
  external:
    name: traefik-net
    external: true
  internal: